RISK_KEYWORDS: dict[str, list[str]] = {
    "file_read": [
        "read file",
        "read files",
        "open file",
        "access local file",
        "filesystem",
        "directory",
        "browse files",
        "parse document",
        "scan folder",
        "read config",
        "read log",
    ],
    "file_write": [
        "write file",
        "save file",
        "create file",
        "modify file",
        "edit file",
        "update file",
        "delete file",
        "remove file",
        "move file",
        "rename file",
    ],
    "network_access": [
        "api request",
        "http request",
        "https request",
        "fetch url",
        "webhook",
        "internet access",
        "remote service",
        "external api",
        "send request",
        "connect to",
        "call api",
    ],
    "shell_exec": [
        "shell command",
        "terminal command",
        "run command",
        "execute command",
        "subprocess",
        "bash",
        "powershell",
        "cli command",
        "os command",
        "script execution",
    ],
    "secrets_access": [
        "environment variable",
        "env var",
        "api key",
        "token",
        "secret",
        "credential",
        "auth header",
        "access key",
        "bearer token",
    ],
    "external_download": [
        "download file",
        "download script",
        "install package",
        "pull binary",
        "fetch remote file",
        "retrieve remote asset",
        "download binary",
    ],
    "app_access": [
        "gmail",
        "email",
        "inbox",
        "calendar",
        "contacts",
        "browser",
        "chrome",
        "slack",
        "discord",
        "drive",
        "notion",
        "chat history",
    ],
}

RISK_WEIGHTS: dict[str, int] = {
    "file_read": 10,
    "file_write": 25,
    "network_access": 15,
    "shell_exec": 35,
    "secrets_access": 30,
    "external_download": 20,
    "app_access": 20,
    "unclear_docs": 10,
}

