import type { SkillDetailResponse, SkillListItem } from "./api";

export const demoSkills: SkillListItem[] = [
  {
    name: "OpenClaw Workflow Runner",
    slug: "openclaw-workflow-runner",
    description: "Automates multi-step OpenClaw workflows with reusable task templates.",
    category: "automation",
    stars: 184,
    last_repo_updated_at: "2026-02-18T10:00:00Z",
    risk_level: "MEDIUM",
  },
  {
    name: "OpenClaw Secrets Auditor",
    slug: "openclaw-secrets-auditor",
    description: "Scans manifests and READMEs for risky permission patterns and secret access hints.",
    category: "security",
    stars: 241,
    last_repo_updated_at: "2026-01-30T15:10:00Z",
    risk_level: "HIGH",
  },
  {
    name: "OpenClaw Prompt Studio",
    slug: "openclaw-prompt-studio",
    description: "Interactive prompt tuning workspace for skill maintainers and reviewers.",
    category: "developer-tools",
    stars: 129,
    last_repo_updated_at: "2026-02-04T08:20:00Z",
    risk_level: "LOW",
  },
  {
    name: "OpenClaw Network Bridge",
    slug: "openclaw-network-bridge",
    description: "Provides controlled network calls for approved connectors and sync jobs.",
    category: "integration",
    stars: 96,
    last_repo_updated_at: "2026-01-21T06:40:00Z",
    risk_level: "CRITICAL",
  },
  {
    name: "OpenClaw Config Advisor",
    slug: "openclaw-config-advisor",
    description: "Guides teams through safer permission defaults and rollout checklists.",
    category: "governance",
    stars: 73,
    last_repo_updated_at: "2026-02-10T13:45:00Z",
    risk_level: "MEDIUM",
  },
];

export const demoSkillDetails: Record<string, SkillDetailResponse> = {
  "openclaw-workflow-runner": {
    name: "OpenClaw Workflow Runner",
    slug: "openclaw-workflow-runner",
    repo_url: "https://github.com/demo/openclaw-workflow-runner",
    repo_owner: "demo",
    repo_name: "openclaw-workflow-runner",
    description: "Automates multi-step OpenClaw workflows with reusable task templates.",
    category: "automation",
    stars: 184,
    last_repo_updated_at: "2026-02-18T10:00:00Z",
    readme_summary:
      "Workflow Runner executes chained task plans, supports retries, and can invoke shell-based setup scripts.",
    latest_risk_report: {
      id: 9001,
      skill_id: null,
      input_type: "skill",
      scanned_at: "2026-02-18T10:00:00Z",
      risk_level: "MEDIUM",
      risk_score: 58,
      flags: {
        file_read: true,
        file_write: true,
        network_access: false,
        shell_exec: true,
        secrets_access: false,
        external_download: false,
        app_access: false,
        unclear_docs: false,
      },
      matched_keywords: {},
      reasons: ["Uses local file mutation and shell execution for automation steps."],
      recommendations: [
        "Run in a scoped workspace and review shell command allow-lists.",
        "Use dry-run mode before enabling write actions in production.",
      ],
    },
  },
  "openclaw-secrets-auditor": {
    name: "OpenClaw Secrets Auditor",
    slug: "openclaw-secrets-auditor",
    repo_url: "https://github.com/demo/openclaw-secrets-auditor",
    repo_owner: "demo",
    repo_name: "openclaw-secrets-auditor",
    description: "Scans manifests and READMEs for risky permission patterns and secret access hints.",
    category: "security",
    stars: 241,
    last_repo_updated_at: "2026-01-30T15:10:00Z",
    readme_summary:
      "Secrets Auditor evaluates permission declarations and flags over-privileged skill setups.",
    latest_risk_report: {
      id: 9002,
      skill_id: null,
      input_type: "skill",
      scanned_at: "2026-01-30T15:10:00Z",
      risk_level: "HIGH",
      risk_score: 77,
      flags: {
        file_read: true,
        file_write: false,
        network_access: true,
        shell_exec: false,
        secrets_access: true,
        external_download: false,
        app_access: true,
        unclear_docs: false,
      },
      matched_keywords: {},
      reasons: ["Reads sensitive files and accesses secrets in connected app contexts."],
      recommendations: [
        "Require approval before reading secret material.",
        "Restrict connector scopes to minimum required permissions.",
      ],
    },
  },
};
